# Binaries build configuration

name: Binary builds

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-10.15, macos-11.0]
    steps:
      # Checkout, fetch-depth=0 fetches the full repos (required for automatic versioning to work)
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: |
          brew install python@3.9 sdl2 libusb
          brew link --overwrite python@3.9
          pip3 install -e .
          pip3 install cx_freeze~=6.4
      
      - name: Build
        run: python3 setup.py bdist_mac
      
      - name: Archive
        run: |
          export VERSION=$(pip3 list | grep cfclient | awk '{print $2}')
          cd build
          zip -r "cfclient_$VERSION.zip" "Crazyflie client.app"
          cd ..
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: ${{ matrix.os }}-build
          path: "build/*.zip"
  
  windows-build:
    runs-on: windows-2019

    steps:
      # Checkout, fetch-depth=0 fetches the full repos (required for automatic versioning to work)
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          pip install -e .
          python tools\build\prep_windows
          pip install cx_freeze~=6.4

      - name: Build exe
        run: python setup.py install_exe -d windows_build
      
      - name: Test exe
        run: windows_build\cfclient.exe --check-imports
      
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.1.4
        with:
          name: windows-build
          path: "windows_build\*"

