# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Checkout, fetch-depth=0 fetches the full repos (required for automatic versioning to work)
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - run: docker pull bitcraze/builder
      
      - name: CI checks
        run: docker run --rm -v ${PWD}:/module bitcraze/builder ./tools/build/build
  
